# KY-040 enkoder
sensor:
  - platform: rotary_encoder
    name: "Encoder"
    pin_a: ${encoder_clk}
    pin_b: ${encoder_dt}
    id: encoder_rot
    resolution: 4
    on_rotate:
      - lambda: |-
          // logika zmiany wartości IP, maski, gateway, DHCP/static
          // zapis do globals
          // Przykład: zmiana adresu Modbus przez obrót
          if (x > id(modbus_address).state) {
            id(modbus_address).state++;
          } else {
            id(modbus_address).state--;
          }
    on_clockwise:
      - lambda: |-
          int m = id(network_mode_global);
          if (m < 4) id(network_mode_global) = m + 1;
    on_anticlockwise:
      - lambda: |-
          int m = id(network_mode_global);
          if (m > 1) id(network_mode_global) = m - 1;
switch:
  - platform: gpio
    pin: 
      number: ${encoder_sw}
      inverted: true
      mode: INPUT_PULLUP
    name: "Encoder Button"
    id: encoder_sw_btn
    on_press:
      then:
        - logger.log: "Przycisk naciśnięty - zatwierdź zmiany"
        - lambda: 'id(modbus_address).execute_restore();' # Przykładowy zapis do flash

# Przycisk enkodera jako zatwierdzenie i Reboot
binary_sensor:
  - platform: gpio
    pin: ${encoder_sw}
    on_press:
      - lambda: |-
          id(network_mode_global).execute_restore();
          App.reboot();
