# Copyright 2026 MichalWerszner
# Globalne zmienne i sensory systemowe

globals:
  # --- Network Mode Control ---
  # 1: LAN DHCP, 2: WiFi DHCP, 3: WiFi AP, 4: Manual Static
  - id: network_mode_global
    type: int
    restore_value: yes
    initial_value: '1'
  
  # --- UI & Interakcja ---
  - id: oled_page
    type: int
    restore_value: no
    initial_value: '0'
  - id: relay_page
    type: int
    restore_value: no
    initial_value: '0'
  - id: is_editing
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: encoder_old_pos
    type: int
    initial_value: '0'
  
  # --- LAN / DHCP Config ---
  - id: lan_dhcp
    type: bool
    restore_value: yes
    initial_value: 'true'
  
  # --- LAN / Static Config ---    
  - id: lan_ip
    type: std::string
    restore_value: yes
    initial_value: '"192.168.1.100"'
  - id: lan_gateway
    type: std::string
    restore_value: yes
    initial_value: '"192.168.1.1"'
  - id: lan_mask
    type: std::string
    restore_value: yes
    initial_value: '"255.255.255.0"'

  # Modbus Parametry
  - id: modbus_baud
    type: int
    restore_value: yes
    initial_value: '${baud_rate}'
  - id: modbus_address
    type: int
    restore_value: yes
    initial_value: '${modbus_inverter_address}'

# Sensory systemowe
sensor:
  - platform: uptime
    id: uptime_sensor
    update_interval: 60s



